-- Insert initial data into the Product table with soft drink brands
INSERT INTO product_table (sku, title_x, price, created_at, updated_at)
VALUES
('SKU001', 'Coca-Cola', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU002', 'Pepsi', 1.89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU003', 'Sprite', 1.79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU004', 'Mountain Dew', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU005', 'Fanta', 1.69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU006', 'Dr Pepper', 2.09, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU007', '7Up', 1.89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU008', 'Mirinda', 1.79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU009', 'Thums Up', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU010', 'Limca', 1.69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU011', 'Diet Coke', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU012', 'Coca-Cola Zero', 2.09, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU013', 'Pepsi Max', 1.89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU014', 'Mountain Dew Zero', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU015', 'Fanta Zero', 1.69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU016', 'Dr Pepper Zero', 2.09, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU017', '7Up Free', 1.89, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU018', 'Mirinda Orange', 1.79, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU019', 'Thums Up Charged', 1.99, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('SKU020', 'Limca Zero', 1.69, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
